#!/bin/bash

commands=$@

# Check if the command is no empty
if [ -z "$commands" ]; then
    echo "No command specified"
    echo "Execute 'waitforlift <long_command>' to play a little music during the <long_command> execution"
    exit 1
fi

exec $commands &

cmdpid=$! # Get the pid from the command
music=$(cat /usr/share/waitforlift/waitforlift.conf)
mpv $music --loop &> /dev/null &
while [ 1 ]
do
    ps -p $cmdpid > /dev/null
    if [[ $? -ne 0 ]]; then
        pkill -9 mpv &> /dev/null
        break
    fi
    sleep 1
done &> /dev/null # Ignore the output when the process is killed by ctrl c via interrupt_command()
