#!/bin/bash
# Script by Valentin Rudloff

trap ctrl_c INT

function ctrl_c() {
    echo "I'll take the stairs..."
    kill -9 $!
    pkill -9 mpv &> /dev/null
    trap - INT
}

cmdpid=$! # get the pid of the last command
music=$(cat /usr/share/waitforlift/waitforlift.conf)
mpv $music --loop &> /dev/null &> /dev/null
while [ 1 ]
do
    ps -p $cmdpid > /dev/null
    if [[ $? -ne 0 ]]; then
        pkill -9 mpv &> /dev/null
        break
    fi
    sleep 1
done