#!/bin/bash
echo "Install autocompletion capabilities for waitforlift script"

# create the bash-completion folder if needed
if [ ! -d /etc/bash_completion.d ]; then
    mkdir -p /etc/bash_completion.d
fi

# Permits the autocompletion of the waitforlift command
echo "complete -F _command waitforlift" > /etc/bash_completion.d/waitforlift
 
echo "log out -> log in again to use the autocompletion capabilities"
echo "or run 'source ~/.bashrc'"