#!/bin/bash
echo "Uninstall autocompletion capabilities for waitforlift script"

# remove the completion if it exists
if [ -f /etc/bash_completion.d/waitforlift ]; then
    rm /etc/bash_completion.d/waitforlift
fi

echo "log out -> log to finish the uninstallation"
echo "or run 'source ~/.bashrc'"