#!/bin/bash

echo "Uninstalling waitforlift script..."
echo "Removing waitforlift script from /usr/bin..."

# Remove entry from bashrc
# TODO error if not found
#echo "Removing entry from ~/.bashrc..."
#sed -i '/# WaitForLift script. Do not remove or modify this script/d' ~/.bashrc
#sed -i '/. \/usr\/share\/waitforlift\/waitforlift/d' ~/.bashrc
#sed -i '$ d' ~/.bashrc
#source ~/.bashrc

# ask for remove conf
#read -p "Do you want to remove the waitforlift script? (y/n) " -n 1 -r